<?xml version = "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>


    <gazebo reference="right_front_wheel">
        <material>Gazebo/Grey</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <gazebo reference="right_back_wheel">
        <material>Gazebo/Grey</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <gazebo reference="left_front_wheel">
        <material>Gazebo/Grey</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <gazebo reference="left_back_wheel">
        <material>Gazebo/Grey</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <!--Controller of the wheel-->
    <gazebo>
        <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">


            <!-- Update rate in Hz -->
            <update_rate>50</update_rate>

            <!--Number of wheel Pairs-->
            <num_wheel_pairs>2</num_wheel_pairs>

            <!--wheels_front-->
            <left_joint>front_left_wheel_joint</left_joint>
            <right_joint>front_right_wheel_joint</right_joint>

            <!--wheels_rear-->
            <left_joint>rear_left_wheel_joint</left_joint>
            <right_joint>rear_right_wheel_joint</right_joint>

            <!-- kinematics -->
            <wheel_separation>${chassis_width + wheel_width}</wheel_separation>
            <wheel_separation>${chassis_width + wheel_width}</wheel_separation>


            <wheel_diameter>${2*wheel_radius}</wheel_diameter>
            <wheel_diameter>${2*wheel_radius}</wheel_diameter>

            <!-- limits -->
            <max_wheel_torque>1000</max_wheel_torque>
            <max_wheel_acceleration>5.0</max_wheel_acceleration>


            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>

        </plugin>
    </gazebo>
</robot>